networks:
    app-tier:
      driver: bridge

services:

  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    container_name: sde_cassandra
    networks:
      - app-tier
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - .:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
        
  jupyter-pyspark:
    build: ./assignment #spark 3.2.1
    container_name: sde_jupyter_spark
    networks:
      - app-tier
    ports:
      - 4040:4040
      - 8888:8888
    volumes:
      - ./assignment:/home/jovyan/work

  fast-api:
    build: ./fastapi-app
    container_name: sde_fast_api
    networks:
      - app-tier
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - ./fastapi-app:/app